"use strict";
// Asset list and version are generated by prepare-site.cjs / the preview server.
const PREFIX = `toki-shell:${self.registration.scope}:`;
const CACHE = PREFIX + '__TOKI_BUILD__';
const ASSETS = /* TOKI_ASSETS */ [];
const urls = new Set(ASSETS.map(file => new URL(file, self.registration.scope).href));
const index = new URL('index.html', self.registration.scope).href;

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Installation succeeds only when the complete app version is available.
    await cache.addAll([...urls].map(url => new Request(url, {cache:'reload'})));
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    await Promise.all((await caches.keys()).filter(name => name.startsWith(PREFIX) && name !== CACHE).map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if (event.data?.type === 'ACTIVATE_UPDATE') event.waitUntil(self.skipWaiting());
});
self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  const root = new URL(self.registration.scope);
  if (url.origin !== root.origin) return;
  const navigation = request.mode === 'navigate' && [root.pathname, new URL(index).pathname].includes(url.pathname);
  // Never cache API responses, private local data, or arbitrary same-origin files.
  url.search = ''; url.hash = '';
  const key = navigation ? index : url.href;
  if (!urls.has(key)) return;
  event.respondWith((async () => {
    const cached = await (await caches.open(CACHE)).match(key);
    return cached || fetch(request);
  })());
});
