const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('shared.js','utf8'),token='a'.repeat(64);
const board=()=>({payload:{schemaVersion:2,people:['Member'],groups:[],dates:[],events:[]},version:1});
function environment(store={board:board()},storage=new Map(),hash=`#share=${token}`){
  let fail=false;const calls=[],notifications=[];
  const client={async rpc(name,args){calls.push({name,args});if(fail)return {error:{message:'offline'}};if(args.p_token!==token)return {error:{message:'LINK'}};if(args.p_action==='save_grouped'){if(args.p_version!==store.board.version)return {error:{message:'CONFLICT'}};store.board={payload:structuredClone(args.p_payload),version:args.p_version+1};}return {data:structuredClone(store.board)};}};
  const window={TOKI_CONFIG:{url:'https://example.supabase.co',publishableKey:'public-test',boardId:'october-2026',siteUrl:'https://example.test/'},TokiSupabase:{createClient:()=>client},addEventListener(){}};
  const document={hidden:false,createElement:()=>({}),head:{append:s=>queueMicrotask(()=>s.onload())},addEventListener(){}};
  vm.runInNewContext(source,{window,document,location:{protocol:'https:',hostname:'example.github.io',search:'',hash},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},URLSearchParams,setInterval:()=>0});
  return {adapter:window.TokiShared,calls,notifications,init(){return window.TokiShared.initialize({board:b=>notifications.push(b),error:e=>notifications.push(e)});},setFailure(){fail=true;}};
}
test('first visitor immediately reads board without registering or adding a row',async()=>{const e=environment();await e.init();assert.equal(e.notifications[0].payload.people.length,1);assert.equal(e.calls.length,1);assert.equal(e.calls[0].args.p_action,'read');assert.equal(Object.hasOwn(e.calls[0].args,'p_registration'),false);});
test('group and roster edits use the versioned grouped save',async()=>{const e=environment();await e.init();const p={...board().payload,groups:[{id:'g',name:'Team',members:[0]}]};const saved=await e.adapter.save(p,1);assert.deepEqual(saved.payload,p);assert.equal(saved.version,2);});
test('two clients cannot overwrite a newer roster or schedule',async()=>{const store={board:board()},a=environment(store),b=environment(store);await a.init();await b.init();await a.adapter.save({...store.board.payload,people:['Renamed']},1);await assert.rejects(b.adapter.save(board().payload,1),e=>e.code==='CONFLICT');assert.equal(store.board.payload.people[0],'Renamed');});
test('stored link works on revisit without participant identity',async()=>{const storage=new Map(),a=environment(undefined,storage);await a.init();const b=environment(undefined,storage,'');await b.init();assert.equal(b.notifications.length,1);});
test('missing or invalid link never exposes the board',async()=>{const a=environment(undefined,undefined,'');await assert.rejects(a.init(),e=>e.code==='LINK');assert.equal(a.calls.length,0);const b=environment(undefined,undefined,`#share=${'b'.repeat(64)}`);await assert.rejects(b.init(),e=>e.code==='LINK');assert.equal(b.notifications.length,0);});
test('network failure does not report save success',async()=>{const e=environment();await e.init();e.setFailure();await assert.rejects(e.adapter.save(board().payload,1),e=>e.code==='NETWORK');});
test('public starter has no private initial names or schedules',()=>{const window={};vm.runInNewContext(fs.readFileSync('data.js','utf8'),{window,location:{protocol:'https:',hostname:'example.github.io'},document:{}});assert.equal(window.TOKI_DATA.people[0],'メンバー1');assert.ok(window.TOKI_DATA.availability.flat().every(v=>v===''));});
